stages:
  economy:
    cmd: PYTHONPATH=. python pipelines/economy/economy.py
    wdir: ../..
    deps:
      - pipelines/economy/economy.py
      - pipelines/util.py
      - raw-data/covid-grants-april-2022.xlsx
      - raw-data/house-prices.xlsx
      - raw-data/unemployment.xlsx
      - raw-data/median-wages.csv
    outs:
      - src/themes/economy/_data/covid_grants_arg.csv:
          cache: false
      - src/themes/economy/_data/covid_grants_ohlg.csv:
          cache: false
      - src/themes/economy/_data/wages.csv:
          cache: false
      - src/themes/economy/_data/house_prices.csv:
          cache: false
      - src/themes/economy/_data/house_price_wage_ratio.csv:
          cache: false
      - src/themes/economy/_data/unemployment_rate.csv:
          cache: false